/** @type {import("@ianvs/prettier-plugin-sort-imports").PrettierConfig} */

export default {
  singleQuote: false,
  semi: true,
  tabWidth: 2,
  plugins: [
    "@ianvs/prettier-plugin-sort-imports",
    "prettier-plugin-tailwindcss",
  ],
  importOrder: [
    "<THIRD_PARTY_MODULES>",
    "",
    "<BUILTIN_MODULES>",
    "",
    "^~/components(.*)$",
    "",
    "^~/config(.*)$",
    "",
    "^~/constants(.*)$",
    "",
    "^~/controllers(.*)$",
    "",
    "^~/cookies(.*)$",
    "",
    "^~/emails(.*)$",
    "",
    "^~/errors(.*)$",
    "",
    "^~/hooks(.*)$",
    "",
    "^~/logger(.*)$",
    "",
    "^~/middleware(.*)$",
    "",
    "^~/routes(.*)$",
    "",
    "^~/schemas(.*)$",
    "",
    "^~/service(.*)$",
    "",
    "^~/types(.*)$",
    "",
    "^~/utils(.*)$",
    "",
    "^[./]",
  ],
};
