const PERMISSIONS = {
  CREATE_ROLE: "CREATE_ROLE",
  READ_ROLE: "READ_ROLE",
  UPDATE_ROLE: "UPDATE_ROLE",
  DELETE_ROLE: "DELETE_ROLE",

  CREATE_USER: "CREATE_USER",
  READ_USER: "READ_USER",
  UPDATE_USER: "UPDATE_USER",
  DELETE_USER: "DELETE_USER",

  CREATE_PROFILE: "CREATE_PROFILE",
  UPDATE_PROFILE: "UPDATE_PROFILE",
  READ_PROFILE: "READ_PROFILE",
  DELETE_PROFILE: "DELETE_PROFILE",

  CREATE_FILE: "CREATE_FILE",
  READ_FILE: "READ_FILE",
  UPDATE_FILE: "UPDATE_FILE",
  DELETE_FILE: "DELETE_FILE",
} as const;

export default PERMISSIONS;
