const PRISMA_ERROR_CODES = {
  UNIQUE_CONSTRAINT_FAILED: "P2002",
  OPERATION_FAILED_AS_RECORD_NOT_FOUND: "P2025",
  FOREIGN_KEY_CONSTRAINT_FAILED: "P2003",
} as const;

export default PRISMA_ERROR_CODES;
